### ISSUE TITLE
ERC1155 access control default in UI does not look enabled

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/contracts-wizard#152]
ERC1155 has Updatable URI enabled by default, which implies (forces) Access Control to be enabled.

In the UI, Access Control is greyed out but does not appear enabled (even though it is enabled in the resulting code).
<img width="256" alt="Screen Shot 2022-07-18 at 10 11 05 AM" src="https://user-images.githubusercontent.com/29640130/179530721-35c12840-d28e-4325-830e-f97f910b4131.png">

**Comment by frangio** [comment]
Seems like a problem with the defaults here, right?

https://github.com/OpenZeppelin/contracts-wizard/blob/cf2496617f5a03223331fb385896bd484a3865e4/packages/core/src/erc1155.ts#L28-L29

**Comment by ericglau** [comment]
Access Control should be implied and not explicitly set as a default.  So that if Updatable URI is disabled in the UI, it should disable Access Control unless the user had selected it.
