### ISSUE TITLE
Implement Cairo 0.10 syntax changes

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/contracts-wizard#173]
In Cairo 0.10 the syntax will change from Python-like to curly braces.

See [Syntax Changes section on this document](https://starkware.notion.site/starkware/StarkNet-0-10-0-4ac978234c384a30a195ce4070461257).

We have to synchronize this with the relevant release of OpenZeppelin Contracts for Cairo. https://github.com/OpenZeppelin/cairo-contracts/issues/403

This will come in about a couple of weeks.

**Comment by ericglau** [comment]
A draft of the expected changes are available in the following branch: https://github.com/OpenZeppelin/contracts-wizard/tree/cairo/0.10

**Comment by martriay** [comment]
any blockers on our side for this? if not, what's the ETA?

**Comment by ericglau** [comment]
This is ready for release, pending the non-beta release of Contracts for Cairo v0.4.0.  Or we can just release it and target v0.4.0b if you prefer.
