### ISSUE TITLE
Add support for solidity ERC777 token

### ISSUE THREAD

**Issue by satya1807** [OpenZeppelin/contracts-wizard#176]
Add ERC777 token with
- access control [ownable, roles]
- mintable
- upgradeable
- premint

**Comment by frangio** [comment]
We are not interested in support ERC-777 in Contracts Wizard at the moment. There is a proposal to deprecate the contract and we might go forward with that route. See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2620
