### ISSUE TITLE
Download Hardhat: add development network file to .gitignore

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/contracts-wizard#204]
If Download -> Development Package (Hardhat) is used with Upgradeability, add the `.openzeppelin/unknown-31337.json` file to the resulting .gitignore (so that the development network file for the Hardhat Upgrades Plugin is ignored).

Also consider possibly different naming conventions depending on https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/645

**Comment by frangio** [comment]
I think you mean https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/465 ?

**Comment by ericglau** [comment]
Both. If differently named files are written during tests, those should also be ignored.

**Comment by frangio** [comment]
Yes, though alternatively we should be writing network files in `/tmp`, which is mentioned in https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/465 as well. In that case there would be nothing to ignore. I think this is the ideal scenario.

**Comment by ericglau** [comment]
This is no longer needed due to https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/726, because manifests for Hardhat dev networks will be written under `/tmp` instead.

**Comment by aashborn** [comment]
Hi,
But this documentation should be updated to reflect this change, right?: https://docs.openzeppelin.com/upgrades-plugins/1.x/
I had to come across this issue to understand why I can't find the network file at the root of my Hardhat project anymore.

**Comment by ericglau** [comment]
Hi @aashborn, thanks for pointing this out.  We updated https://docs.openzeppelin.com/upgrades-plugins/1.x/network-files#temporary-files but missed that page.  Could you please open a new issue?  

By the way, could you let us know what is your use case that led you to look for that file for Hardhat?

**Comment by aashborn** [comment]
My bad, I had missed this section! I had upgraded to a higher version of Hardhat and I was confused not to see this file anymore🙂

Currently I would just like to use this file to study the variation of the storage layout. I know that this information can also be produced with the compiler options, but as I was saying I also wanted to know why I was not seeing the network file anymore.
