### ISSUE TITLE
Link readme image to wizard.openzeppelin.com

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/contracts-wizard#214]
The README.md has a screenshot of Wizard.  Clicking the screenshot just opens a larger image which isn't useful.  Instead, clicking the image should go to https://wizard.openzeppelin.com/ instead.

**Comment by c00kie123** [comment]
Hey, I can help in this! Assign it to me .

**Comment by Rishav1707** [comment]
> The README.md has a screenshot of Wizard. Clicking the screenshot just opens a larger image which isn't useful. Instead, clicking the image should go to https://wizard.openzeppelin.com/ instead.

Can I?
