### ISSUE TITLE
Use token-specific pausable extensions

### ISSUE THREAD

**Issue by SKYBITDev3** [OpenZeppelin/contracts-wizard#285]
At https://docs.openzeppelin.com/contracts/5.x-rc/wizard or https://wizard.openzeppelin.com when selecting Pausable it imports `Pausable` instead of `ERC20Pausable` or `ERC1155Pausable` etc.

`ERC20Pausable` etc. were even available in 4.x (https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#ERC20Pausable) so the wizard should produce such newer code.

**Comment by ericglau** [comment]
Note that OpenZeppelin Contracts 5.0 support will be added in https://github.com/OpenZeppelin/contracts-wizard/pull/284.  At the moment Wizard targets 4.x.

Using Pausable and adding/overriding the relevant functions would be equivalent to using the token-specific pausable extensions, but the extensions can be used to simplify the code.  It makes sense to add them to Wizard.
