### ISSUE TITLE
Add Cairo lang and OZ Contracts versions to generated contracts

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/contracts-wizard#319]
Right now users have no way of knowing what OZ Contracts version they're generating nor what Cairo compiler version to use with. We can add these in the comments (right next to the licence).

Another alternative is to specify just Contracts version and have (assume?) a mapping between OZ Contracts <> Cairo version.

**Comment by ericglau** [comment]
For Solidity, we plan to convey semantic versioning for the OZ Contracts version like this:
```
// SPDX-License-Identifier: MIT
// Compatible with OpenZeppelin Contracts ^5.0.0
pragma solidity ^0.8.20;
```

@martriay @ericnordelo @andrew-fleming For Cairo, does it make sense to also convey semantic versioning for Cairo lang itself?  For example, something like:
```
// SPDX-License-Identifier: MIT
// Compatible with OpenZeppelin Contracts for Cairo ^0.8.0
// Cairo lang ^2.3.1
```
(or `// Cairo compiler ^2.3.1`)

**Comment by martriay** [comment]
Looks good! Although I'd be very specific with the versions since Cairo is introducing breaking changes even in minor releases. We cannot guarantee compatibility with any future version.

**Comment by martriay** [comment]
Specific version > no version
