### ISSUE TITLE
Change version of solidity (Generate 0.8.19 instead of 0.8.26)

### ISSUE THREAD

**Issue by AxelGUILLAUMET** [OpenZeppelin/contracts-wizard#377]
-

**Comment by ericglau** [comment]
Can you provide more detail for what you need?

Wizard generates contracts with `pragma solidity ^0.8.20` to match the requirements for OpenZeppelin Contracts 5.0, for the reasons explained in [this comment](https://forum.openzeppelin.com/t/why-is-there-a-restrictive-pragma-on-interfaces-in-the-5-0-2-release/41311/3).

**Comment by ericglau** [comment]
Closing as described above. Feel free to reopen if needed.
