### ISSUE TITLE
Backslack in Windows Instead of Forward Slash on Yarn

### ISSUE THREAD

**Issue by fizyliftingdrnks** [OpenZeppelin/contracts-wizard#44]
While using yarn in Windows, when trying to open the UI, the last line on import is a backslash instead of a forward slash.  This causes an issue while trying to compile in yarn.

Not sure if this is an issue as well within Linux, but something worth investigating.

![Capture](https://user-images.githubusercontent.com/87679864/126417330-f4890a7d-8017-4bc4-b817-9ccb746c6319.JPG)

**Comment by frangio** [comment]
Should be fixed on `master`.

I'm curious, why are you setting up this repository locally?
