### ISSUE TITLE
Add "upgradeability" toggle

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/contracts-wizard#7]
This is an area where the Wizard can add a ton of value. Particularly around initializers.

**Comment by abcoathup** [comment]
Especially when using multiple inheritance and needing to use unchained initializers.

**Comment by DeAppx** [comment]
Yes, it would be great!

**Comment by buschmann** [comment]
by the way, i am missing "track" and "deep-track" / Consecutive Transfer Extensions ... ?

**Comment by DeAppx** [comment]
I am waiting for an upgradable function to deploy my token contract. The earliest possible would be much more appreciated

**Comment by buschmann** [comment]
... be happy, i am still by finding a way to produce the right contract with functions and all that it can fit in the game... 
.. but "jipppie" an upgradeable_function i will need of sure also ++

**Comment by frangio** [comment]
@buschmann  OpenZeppelin Contracts doesn't yet have Consecutive Transfer Extensions. See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2355.

@DeAppx This is the next feature in the roadmap for Contacts Wizard but I don't think it will be released in less than a month. I would recommend you get started by generating the contract that you want and then consulting [this part of the documentation](https://docs.openzeppelin.com/contracts/4.x/upgradeable) ot make it upgradeable, together with the [Upgrades Plugins](https://zpl.in/docs/upgrades).

**Comment by buschmann** [comment]
THX, and "uff" a month is long, sad that i cant help by this ... 
But it is as it is, without the function the game production must wait a bit. :( 
The idea with upgrade is fine, i am also by reading it, how it runs for the bsc...

**Comment by itxlieni** [comment]
Hi any progress here allready? Would also love to see the update

**Comment by frangio** [comment]
@itxlieni Working on this since a few days ago, expect it later this week!
