### ISSUE TITLE
Add global toggle for "Access Control" section

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/contracts-wizard#82]
... like the Upgradeability section, and make sure that if it is enabled then the contract is actually inherited. Currently even if Ownable is selected, unless a feature like Mintable makes use of it the resulting contract will not have Ownable and this could be confusing for users.

**Comment by ericglau** [comment]
For features that do use access control (e.g. Mintable, Pausable, UUPS Upgradeable), we should make Access Control required if those features are enabled.  Otherwise anyone would be able to mint or pause or upgrade.
