### ISSUE TITLE
Use `immutable` for OpenZeppelin AccessControl's Roles Declarations

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/contracts-wizard#89]
Access roles marked as `constant` results in computing the `keccak256` operation each time the variable is used because assigned operations for `constant` variables are re-evaluated every time. Changing the variables to `immutable` results in computing the hash only once on deployment, leading to gas savings. Some background information can be found [here](https://github.com/code-423n4/2021-10-slingshot-findings/issues/3) and [here](https://github.com/ethereum/solidity/issues/9232#issuecomment-646131646).

**Comment by frangio** [comment]
Your observation is correct about `constant` variables in general, but `keccak256` of string literals is treated specially and the hash is evaluated at compile time. It's not even necessary to have optimizations enabled. You can see this in the changelog items for [0.6.12](https://github.com/ethereum/solidity/blob/develop/Changelog.md#0612-2020-07-22), and I've just confirmed that this is the way it works currently.

**Comment by pcaversaccio** [comment]
Yeah, you are right - thanks for the clarification. For the sake of completeness, there is however a general issue that is still open: https://github.com/ethereum/solidity/issues/3157.

**Comment by pcaversaccio** [comment]
@frangio your `_PERMIT_TYPEHASH` variable is however declared as `immutable` [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/draft-ERC20Permit.sol#L28). Is there a specific reason? Otherwise, I would propose to make this `constant` as well due to the sake of consistency (happy to make a PR).
